- BLL/AreaBLL.cs
- BLL/BLL.csproj
- BLL/TableBLL.cs
- DAL/Area.cs
- DAL/Department.cs
- DAL/Employee.cs
- DAL/Menu.cs
- DAL/MenuItem.cs
- DAL/Order.cs
- DAL/Table.cs
- GUI/AddAreaDialog.Designer.cs
- GUI/AddAreaDialog.cs
- GUI/AddAreaDialog.resx
- GUI/GUI.csproj
- GUI/Login.Designer.cs
- GUI/Login.cs
- GUI/Program.cs
- GUI/RestaurantSetup.Designer.cs
- GUI/RestaurantSetup.cs
- GUI/RestaurantSetup.resx
- GUI/SeatSetup.Designer.cs
- GUI/SeatSetup.cs
- GUI/SeatSetup.resx
- GUI/TableControl.Designer.cs
- GUI/TableControl.cs
- GUI/TableControl.resx
READY
Allow user can create a new area
> [Feature] Create an area

- BLL/TableBLL.cs
- GUI/SeatSetup.cs
- GUI/TableControl.Designer.cs
- GUI/TableControl.cs
- GUI/TableControl.resx
READY
Users can delete a table.
> [Feature] Emplement delete table

- GUI/GUI.csproj
- GUI/SeatSetup.Designer.cs
- GUI/SeatSetup.cs
- GUI/TableAddDialog.Designer.cs
- GUI/TableAddDialog.cs
- GUI/TableAddDialog.resx
> [Feature] Create table

- README.md
> [Feature] Update migrate database

- DAL/Table.cs
> [Feature] Update tabledb

- BLL/BLL.csproj
- BLL/Connection.cs
- BLL/OrderBLL.cs
- GUI/Control/SelectMenuItemControl.cs
- GUI/Control/TableControl.cs
- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
- GUI/StaffWorking/TablesStatus.Designer.cs
- GUI/StaffWorking/TablesStatus.cs
- GUI/StaffWorking/TablesStatus.resx
> [Feature] Show list tables by status

- BLL/AreaBLL.cs
- BLL/DepartmentBLL.cs
- BLL/EmloyeeDepartmentBLL.cs
- BLL/EmployeeBLL.cs
- BLL/MenuBLL.cs
- BLL/MenuItemBLL.cs
- BLL/TableBLL.cs
- BLL/UserBLL.cs
- GUI/StaffWorking/CreateOrder.cs
- GUI/StaffWorking/TablesStatus.cs
> [Fix] Fix order null

- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
> [Feature] Setup for vat extra discount changetable pay

- BLL/OrderBLL.cs
- GUI/AddDiscountDialog.Designer.cs
- GUI/AddDiscountDialog.cs
- GUI/AddDiscountDialog.resx
- GUI/GUI.csproj
- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
> [Feature] Add discount

- BLL/OrderBLL.cs
- DAL/Order.cs
- GUI/AddExtraDialog.Designer.cs
- GUI/AddExtraDialog.cs
- GUI/AddExtraDialog.resx
- GUI/GUI.csproj
- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
> [Feature] Add extra

- BLL/OrderBLL.cs
- GUI/Control/SelectMenuItemControl.cs
- GUI/GUI.csproj
- GUI/StaffWorking/AddVAT.Designer.cs
- GUI/StaffWorking/AddVAT.cs
- GUI/StaffWorking/AddVAT.resx
- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
> [Feature] Add vat

- BLL/OrderBLL.cs
- BLL/TableBLL.cs
- GUI/AddDiscountDialog.Designer.cs
- GUI/AddDiscountDialog.cs
- GUI/GUI.csproj
- GUI/Program.cs
- GUI/StaffWorking/AddVAT.cs
- GUI/StaffWorking/ChangeTable.Designer.cs
- GUI/StaffWorking/ChangeTable.cs
- GUI/StaffWorking/ChangeTable.resx
- GUI/StaffWorking/CreateOrder.Designer.cs
- GUI/StaffWorking/CreateOrder.cs
- GUI/StaffWorking/TablesStatus.cs
> [Feature] Change tables

- BLL/AnalyticsBLL.cs
- GUI/Analytics.Designer.cs
- GUI/Analytics.cs
- GUI/Analytics.resx
- GUI/GUI.csproj
> [Feature] Export analytic to an excel file

- GUI/Control/TableControl.cs
- GUI/SystemSetup/Menu/AddMenu.cs
- GUI/SystemSetup/RestaurantSetup.Designer.cs
> [Fixbug] feature change table, edit menu

- BLL/OrderBLL.cs
- BLL/TableBLL.cs
- GUI/Analytics.cs
- GUI/Control/SelectMenuItemControl.Designer.cs
- GUI/Control/SelectMenuItemControl.cs
- GUI/FeatureSelector.cs
- GUI/GUI.csproj
- GUI/Login.Designer.cs
- GUI/StaffWorking/ChangeTable.Designer.cs
- GUI/StaffWorking/ChangeTable.cs
- GUI/StaffWorking/CreateOrder.cs
- GUI/StaffWorking/TablesStatus.cs
- GUI/SystemSetup/Department/DepartmentSetup.cs
- GUI/SystemSetup/Menu/MenuSetup.cs
- GUI/SystemSetup/RestaurantSetup.cs
- GUI/SystemSetup/Seat/SeatSetup.cs
- GUI/Utilities/UtilsForm.cs
> [Feature] Remove food from order

- BLL/OrderBLL.cs
- BLL/TableBLL.cs
- GUI/Analytics.cs
- GUI/Control/SelectMenuItemControl.Designer.cs
- GUI/Control/SelectMenuItemControl.cs
- GUI/FeatureSelector.cs
- GUI/GUI.csproj
- GUI/Login.Designer.cs
- GUI/StaffWorking/ChangeTable.Designer.cs
- GUI/StaffWorking/ChangeTable.cs
- GUI/StaffWorking/CreateOrder.cs
- GUI/StaffWorking/TablesStatus.cs
- GUI/SystemSetup/Department/DepartmentSetup.cs
- GUI/SystemSetup/Menu/MenuSetup.cs
- GUI/SystemSetup/RestaurantSetup.cs
- GUI/SystemSetup/Seat/SeatSetup.cs
- GUI/Utilities/UtilsForm.cs
> [Feature] Remove food from order (#27)

- DAL/App.config
- DAL/Migrations/Configuration.cs
- GUI/App.config
- GUI/Program.cs
> [Feature] attach db (#32)

- .gitignore
> [Feature] Add mdf db

- .gitignore
> [Feature] Add mdf db (#34)

- BLL/OrderBLL.cs
> [Hotfix] Fix change/merge table

- GUI/GUI.csproj
- GUI/Properties/Resources.Designer.cs
- GUI/Properties/Resources.resx
- GUI/SystemSetup/Menu/AddFood.cs
> [Hotfix] Fix add food
